"""FD Guardrail Evaluation Script.

Evaluates a trained FNO or DeepONet against the FD ground truth stored in a
generated dataset.  Each sample in the dataset was solved by the FD solver
at 64×64; this script runs the neural solver on the same inputs and computes
per-sample and aggregate error metrics.

Usage (CLI)
-----------
    # Evaluate FNO on a held-out test dataset
    python src/evaluate.py fno \\
        --dataset pretrained_models/val_data \\
        --model   pretrained_models/fno.pt \\
        --width 32 --modes 12 --layers 4

    # Evaluate DeepONet on a held-out test dataset
    python src/evaluate.py deeponet \\
        --dataset pretrained_models/val_data \\
        --model   pretrained_models/deeponet.pt

    # Evaluate FD solver only (sanity-check: should give near-zero error)
    python src/evaluate.py fd \\
        --dataset pretrained_models/val_data

Metrics reported
----------------
    rel_l2   : ‖u_pred − u_fd‖₂ / ‖u_fd‖₂   (relative L2 error)
    rmse     : RMS element-wise error
    max_err  : max |u_pred − u_fd|
    bc_error : BC satisfaction error (from InferenceEngine)
    pde_res  : PDE residual (from InferenceEngine)

Public API
----------
    from evaluate import evaluate_dataset, EvalMetrics
"""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import numpy as np

# Ensure src/ is on path when invoked directly
sys.path.insert(0, str(Path(__file__).parent))

from dataset import load_dataset_artifact
from inference_engine import (
    FDConfig,
    FNOConfig,
    GridConfig,
    InferenceEngine,
    DeepONetConfig,
    SolveResult,
    SolverOption,
)
from pde_parser import parse_bc, parse_pde
from physics.pde_helpers import compute_sample_metrics


# ---------------------------------------------------------------------------
# Metrics dataclass
# ---------------------------------------------------------------------------

@dataclass
class EvalMetrics:
    """Per-sample evaluation metrics comparing neural solver to FD ground truth."""

    rel_l2: float
    rmse: float
    max_err: float
    bc_error: float
    pde_residual: float
    method: str
    is_ood: bool

    def to_dict(self) -> dict[str, Any]:
        return {
            "rel_l2": self.rel_l2,
            "rmse": self.rmse,
            "max_err": self.max_err,
            "bc_error": self.bc_error,
            "pde_residual": self.pde_residual,
            "method": self.method,
            "is_ood": self.is_ood,
        }


def _compute_metrics(
    u_pred: np.ndarray,
    u_fd: np.ndarray,
    result: SolveResult,
) -> EvalMetrics:
    """Compute error metrics between prediction and FD reference."""
    rel_l2, rmse, max_err = compute_sample_metrics(u_pred, u_fd)
    return EvalMetrics(
        rel_l2=rel_l2,
        rmse=rmse,
        max_err=max_err,
        bc_error=result.bc_error,
        pde_residual=result.residual,
        method=result.method,
        is_ood=result.is_ood,
    )


# ---------------------------------------------------------------------------
# Core evaluation loop
# ---------------------------------------------------------------------------

def evaluate_dataset(
    dataset_path: str,
    solver_option: SolverOption,
    n_samples: int | None = None,
    print_every: int = 10,
) -> tuple[list[EvalMetrics], dict[str, float]]:
    """Evaluate the solver on all samples in a dataset file.

    Parameters
    ----------
    dataset_path   : Path to .npz dataset generated by ``trainer.py fno-generate``.
    solver_option  : SolverOption controlling which solver/model to use.
    n_samples      : Limit evaluation to first N samples; None = all.
    print_every    : Log progress every N samples.

    Returns
    -------
    metrics        : Per-sample EvalMetrics list.
    summary        : Dict of aggregate statistics (mean/std/max for each metric).
    """
    artifact = load_dataset_artifact(dataset_path)
    fd_targets: np.ndarray = artifact.targets
    pde_strs: np.ndarray = artifact.pde_strs
    bc_json: np.ndarray = artifact.bc_json

    total = len(fd_targets)
    if n_samples is not None:
        total = min(total, n_samples)

    engine = InferenceEngine(solver_option=solver_option)
    metrics_list: list[EvalMetrics] = []
    n_ood = 0
    n_failed = 0

    print(f"Evaluating {total} samples with solver={solver_option.solver_type!r} ...")

    for i in range(total):
        pde_str = str(pde_strs[i])
        bc_dict: dict = json.loads(str(bc_json[i]))
        u_fd = fd_targets[i]  # (n, n) FD ground truth

        try:
            result = engine.solve(
                pde_str=pde_str,
                bc_dict=bc_dict,
                print_every=10_000,   # suppress per-iteration output
            )
        except Exception as exc:
            print(f"  Sample {i}: solver failed — {exc}")
            n_failed += 1
            continue

        # Evaluation should compare like-for-like grids; a mismatch usually
        # means the inference resolution does not match the dataset resolution.
        u_pred = result.u
        if u_pred.shape != u_fd.shape:
            print(
                f"  Sample {i}: skipped due to resolution mismatch "
                f"(prediction {u_pred.shape} vs FD target {u_fd.shape})"
            )
            n_failed += 1
            continue
        else:
            u_fd_cmp = u_fd

        m = _compute_metrics(u_pred, u_fd_cmp, result)
        metrics_list.append(m)

        if m.is_ood:
            n_ood += 1

        if (i + 1) % print_every == 0:
            print(
                f"  [{i + 1:>5d}/{total}] "
                f"rel_l2={m.rel_l2:.3e}  rmse={m.rmse:.3e}  "
                f"max={m.max_err:.3e}  method={m.method}"
                + (" [OOD]" if m.is_ood else "")
            )

    if not metrics_list:
        print("No samples evaluated successfully.")
        return [], {}

    # Aggregate
    rel_l2s  = np.array([m.rel_l2 for m in metrics_list])
    rmses    = np.array([m.rmse for m in metrics_list])
    max_errs = np.array([m.max_err for m in metrics_list])
    bc_errs  = np.array([m.bc_error for m in metrics_list])
    pde_res  = np.array([m.pde_residual for m in metrics_list])

    summary = {
        "n_samples": len(metrics_list),
        "n_failed": n_failed,
        "n_ood": n_ood,
        "ood_rate": n_ood / max(len(metrics_list), 1),
        # Relative L2 vs FD ground truth
        "rel_l2_mean": float(np.mean(rel_l2s)),
        "rel_l2_std":  float(np.std(rel_l2s)),
        "rel_l2_p50":  float(np.median(rel_l2s)),
        "rel_l2_p90":  float(np.percentile(rel_l2s, 90)),
        "rel_l2_max":  float(np.max(rel_l2s)),
        # RMSE
        "rmse_mean": float(np.mean(rmses)),
        "rmse_std":  float(np.std(rmses)),
        # Max absolute error
        "max_err_mean": float(np.mean(max_errs)),
        "max_err_max":  float(np.max(max_errs)),
        # BC and PDE residual (self-assessed)
        "bc_error_mean": float(np.mean(bc_errs)),
        "pde_res_mean":  float(np.mean(pde_res)),
    }

    return metrics_list, summary


def _print_summary(summary: dict[str, float], solver_type: str) -> None:
    pad = 45
    print()
    print("=" * pad)
    print(f" Evaluation summary  [solver={solver_type}]")
    print("=" * pad)
    print(f"  Samples evaluated : {summary['n_samples']}")
    if summary["n_failed"]:
        print(f"  Failed            : {summary['n_failed']}")
    if summary["n_ood"]:
        print(f"  OOD (FD fallback) : {summary['n_ood']}  ({summary['ood_rate']:.1%})")
    print()
    print(f"  Relative L2 vs FD ground truth:")
    print(f"    mean  : {summary['rel_l2_mean']:.4e}")
    print(f"    std   : {summary['rel_l2_std']:.4e}")
    print(f"    p50   : {summary['rel_l2_p50']:.4e}")
    print(f"    p90   : {summary['rel_l2_p90']:.4e}")
    print(f"    max   : {summary['rel_l2_max']:.4e}")
    print()
    print(f"  RMSE (mean)       : {summary['rmse_mean']:.4e}")
    print(f"  Max abs err (mean): {summary['max_err_mean']:.4e}")
    print()
    print(f"  BC error  (mean)  : {summary['bc_error_mean']:.4e}")
    print(f"  PDE resid (mean)  : {summary['pde_res_mean']:.4e}")
    print("=" * pad)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def _make_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="FD-guardrail evaluation: compare solver predictions to FD ground truth"
    )
    sub = parser.add_subparsers(dest="solver", required=True)

    # --- shared arguments helper ---
    def _add_shared(p: argparse.ArgumentParser) -> None:
        p.add_argument(
            "--dataset", required=True,
            help="Path to .npz dataset (e.g. pretrained_models/val_data)",
        )
        p.add_argument("--n-samples",   type=int,   default=None,
                       help="Limit to first N samples (default: all)")
        p.add_argument("--print-every", type=int,   default=10,
                       help="Log every N samples (default: 10)")
        p.add_argument("--n-points",    type=int,   default=64,
                       help="Grid resolution for inference (default: 64)")
        p.add_argument("--device",      type=str,   default=None)

    # --- fno sub-command ---
    fno_p = sub.add_parser("fno", help="Evaluate trained FNO vs FD ground truth")
    _add_shared(fno_p)
    fno_p.add_argument("--model",    required=True,
                       help="Path to FNO .pt weights or TorchScript archive")
    fno_p.add_argument("--manifest", type=str, default=None,
                       help="Path to OOD manifest .npz (auto-detected if omitted)")
    fno_p.add_argument("--width",    type=int, default=32)
    fno_p.add_argument("--modes",    type=int, default=12)
    fno_p.add_argument("--layers",   type=int, default=4)

    # --- deeponet sub-command ---
    deeponet_p = sub.add_parser("deeponet", help="Evaluate trained DeepONet vs FD ground truth")
    _add_shared(deeponet_p)
    deeponet_p.add_argument("--model", required=True,
                            help="Path to DeepONet .pt weights")
    deeponet_p.add_argument("--branch-hidden", type=int, default=128)
    deeponet_p.add_argument("--branch-layers", type=int, default=3)
    deeponet_p.add_argument("--trunk-hidden", type=int, default=128)
    deeponet_p.add_argument("--trunk-layers", type=int, default=3)
    deeponet_p.add_argument("--latent-dim", type=int, default=128)

    # --- fd sub-command ---
    fd_p = sub.add_parser("fd", help="Evaluate FD solver against stored FD targets (sanity check)")
    _add_shared(fd_p)
    fd_p.add_argument("--max-iterations", type=int,   default=5000)
    fd_p.add_argument("--tolerance",      type=float, default=1e-5)

    return parser


def _auto_manifest(model_path: str, explicit: str | None) -> str | None:
    """Return an OOD manifest path: explicit override > auto-detect > None."""
    if explicit is not None:
        return explicit
    p = Path(model_path)
    candidates = [p.parent / "manifest.npz"]
    for c in candidates:
        if c.exists():
            return str(c)
    return None


def main() -> None:
    parser = _make_parser()
    args = parser.parse_args()

    if args.solver == "fno":
        manifest = _auto_manifest(args.model, getattr(args, "manifest", None))
        option = SolverOption(
            solver_type="fno",
            device=args.device,
            grid=GridConfig(n_points=args.n_points),
            fno=FNOConfig(
                model_path=args.model,
                manifest_path=manifest,
                width=args.width,
                n_modes=(args.modes, args.modes),
                n_layers=args.layers,
            ),
        )

    elif args.solver == "deeponet":
        option = SolverOption(
            solver_type="deeponet",
            device=args.device,
            grid=GridConfig(n_points=args.n_points),
            deeponet=DeepONetConfig(
                model_path=args.model,
                branch_hidden=args.branch_hidden,
                branch_layers=args.branch_layers,
                trunk_hidden=args.trunk_hidden,
                trunk_layers=args.trunk_layers,
                latent_dim=args.latent_dim,
            ),
        )

    else:  # fd
        option = SolverOption(
            solver_type="fd",
            device=args.device,
            grid=GridConfig(n_points=args.n_points),
            fd=FDConfig(
                max_iterations=args.max_iterations,
                tolerance=args.tolerance,
                print_every=10_000,
            ),
        )

    metrics_list, summary = evaluate_dataset(
        dataset_path=args.dataset,
        solver_option=option,
        n_samples=args.n_samples,
        print_every=args.print_every,
    )

    if summary:
        _print_summary(summary, args.solver)


if __name__ == "__main__":
    main()
